[eusopdw]
host     = "eu-sop-dw1.ct60odtjekom.us-east-1.redshift.amazonaws.com"
port     = 8192
dbname   = "eusopdw"
user     = {type = "string"}
password = {type = "string"}

[insite]
host     = "eu-insite-prod.cchrgqkq6npc.eu-west-1.redshift.amazonaws.com"
port     = 8192
dbname   = "insite"
user     = ""
password = ""

[eucfdw1]
host     = "eu-cf-dw-1.c8901eljftvr.us-east-1.redshift.amazonaws.com"
port     = 8192
dbname   = "eucfdw1"
user     = ""
password = ""

[analyticsengineeu]
host     = "simulation-analytics-eu.cfs2fh8bzc38.eu-west-1.redshift.amazonaws.com"
port     = 8192
dbname   = "analyticsengineeu"
user     = ""
password = ""
